# Generated by Django 5.1.7 on 2025-04-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="role",
        ),
        migrations.AddField(
            model_name="assessment",
            name="job_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Business", "Business"),
                    ("Clerical", "Clerical"),
                    ("Contact Center", "Contact Center"),
                    ("Customer Service", "Customer Service"),
                    ("Information Technology", "Information Technology"),
                    ("Safety", "Safety"),
                    ("Sales", "Sales"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="job_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Director", "Director"),
                    ("Entry-Level", "Entry-Level"),
                    ("Executive", "Executive"),
                    ("Front Line Manager", "Front Line Manager"),
                    ("General Population", "General Population"),
                    ("Graduate", "Graduate"),
                    ("Manager", "Manager"),
                    ("Mid-Professional", "Mid-Professional"),
                    (
                        "Professional Individual Contributor",
                        "Professional Individual Contributor",
                    ),
                    ("Supervisor", "Supervisor"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("English", "English"),
                    ("Spanish", "Spanish"),
                    ("French", "French"),
                    ("German", "German"),
                    ("Chinese", "Chinese"),
                    ("Hindi", "Hindi"),
                    ("Arabic", "Arabic"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Banking/Finance", "Banking/Finance"),
                    ("Healthcare", "Healthcare"),
                    ("Hospitality", "Hospitality"),
                    ("Insurance", "Insurance"),
                    ("Manufacturing", "Manufacturing"),
                    ("Oil & Gas", "Oil & Gas"),
                    ("Retail", "Retail"),
                    ("Telecommunications", "Telecommunications"),
                ],
                max_length=50,
            ),
        ),
    ]
