# Generated by Django 5.1.7 on 2025-04-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_assessment_role_assessment_job_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="google_form_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="task_file",
            field=models.FileField(blank=True, null=True, upload_to="tasks/"),
        ),
    ]
